### ISSUE TITLE
Doesn't work with Subsites module

### ISSUE THREAD

**Issue by purplespider** [mediabeastnz/silverstripe-fancy-devbuild#21]
For some reason if the Subsites module is installed, the $attributes for this CMSMenu link don't appear to take effect:
![](http://spdr.me/18zaC+)

**Comment by gorriecoe** [comment]
The issue appears to be coming from the Subsite module.  The module is missing a variable in LeftAndMain_Menu.ss.  See [Sub sites pull request](https://github.com/silverstripe/silverstripe-subsites/pull/234) for the fix.

**Comment by gorriecoe** [comment]
Subsites has been updated.   If you update to dev master, it should work now :)

**Comment by purplespider** [comment]
Thanks for the heads up!  Yep, working now!
