### ISSUE TITLE
Added permissions

### ISSUE THREAD

**Issue by mylesthedev** [mediabeastnz/silverstripe-fancy-devbuild#3]
Currently the button is injected no matter what permissions the CMS user has. 
This really needs to be controlled with permissions to allow full control.

**Comment by gorriecoe** [comment]
This can probably be marked done now

**Comment by mylesthedev** [comment]
Yup thanks @gorriecoe this was closed by PR https://github.com/mediabeastnz/silverstripe-fancy-devbuild/pull/14
